# Matemática básica no `R`

Aqui mostramos como executar algumas operações aritméticas básicas  e algumas funções no `R`. Trazemos os códigos e ao final um vídeo explicativo com todas as operações listadas.

```{r results=F}
# Soma:
1+3
10+2

# Subtração:
5-2
10-2
2-10

# Multiplicação;
2*3
7*4

# Potenciação
2^3
4^4
2**3
4**4

# Divisão;
8/2
10/3

# Quociente da divisão; parte inteira: %/%
10%/%3

# Resto da divisão: %%
10%%3

# Módulo:
abs(-3)
abs(8)
abs(-10)

# Logarítmo:
log(2)
log(2,10)
log10(2)
?log
help(log)
log(2,exp(1))
log

# Exponencial:
exp(1)
exp(3)
exp(0)

# Pi
pi

# Funções Trigonométricas:
?sin
sin(pi/2)
sinpi(1/2)
cos(pi/2)
cos(pi)
cos(0)
tan(pi/4)
sin(pi/4)/cos(pi/4)

# Fatorial:
factorial(4)
4*3*2*1

# Combinações:
choose(10,2)
10*9/factorial(2)
factorial(10)/(factorial(10-2)*factorial(2))

# Somatórios:
x = 3:13
x
sum(x)
cumsum(x)
max(cumsum(x))
x |> cumsum() |> max()

# Produtórios:
x |> prod()
prod(x)
```

*Link* da aula [Matemática Básica no R:](https://youtu.be/QDLqS3y5u7Q)

```{r, echo=F, results='asis'}
knitr::include_url("https://youtu.be/embed/QDLqS3y5u7Q")
```