--- 
title: "R na Cozinha"
author: "Paulo Guilherme Pinheiro dos Santos"
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
site: bookdown::bookdown_site
documentclass: book
geometry: top=3cm,left=3cm,right=2cm,bottom=2cm
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: pgpinheiro2/R_pg2_book
description: "Este é a minha contribuição ao ensino do R. Foi elaborado graças ao pacote `bookdown`."
url: 'https\://pgpinheiro2.github.io/R_pg2_book/'
fontsize: 12pt
linkcolor: red
citecolor: blue
urlcolor: magenta
lang: pt-br
---

# Apresentação

Neste guia, pretendemos compartilhar nossa experiência no uso do *software* `R` com a comunidade com o objetivo de contribuir com tudo que o programa nos ofereceu ao longo desses anos de uso. 

...


```{r echo=F, message=F}
# Chunk com os Pacotes carregados
library(tidyverse)
library(emo)
```

```{r include=F}
# automatically create a .bib database for R packages; salva os detalhes no arquivo "packages.bib"
knitr::write_bib(
  c(.packages(), 'bookdown', 'knitr', 'rmarkdown'),
  'packages.bib'
  )
```
